version: "3"

services:
  postgres:
    image: matthieuberger/postgres-multi-db:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_MULTIPLE_DATABASES=platform

  temporal:
    restart: on-failure:3
    build:
      context: ./temporal
      dockerfile: Dockerfile
    ports:
      - 7233:7233
      - 8233:8233
    volumes:
      - ./tmp/teamporal:/usr/temporal/

  # API ..service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      NYLAS_API_KEY: nyk_v0_BUmqOUZVax4sT7Gant9OSVXdoeros8g8JpaxOClg5Gty4M46aRu1ixeuuLL9Hgaw
      NYLAS_CLIENT_ID: bd14acbe-a8d3-4ed6-8b00-4589b7acc167
      NYLAS_API_URI: https://api.eu.nylas.com
      NYLAS_GRANT_ID: af350b13-f4b1-4d2d-907c-3f3de8134424
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASES: platform
      SERVER_PORT: 3000
      SUPPORT_NAME: "Mentium Ticket Support"
      SUPPORT_EMAIL: mentiumcodechallenge@outlook.com
    networks:
      - default

  nlp:
    build:
      context: ./nlp
      dockerfile: Dockerfile
    container_name: nlp
    ports:
      - "5004:5004"

  # client:
  #   build:
  #     context: ./webapp
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - server

  #Email Workflow Service
  # email-service:
  #   build:
  #     context: ./email-worker
  #     dockerfile: Dockerfile
  #   command: ["npm", "run", "start:all"]
  #   depends_on:
  #     - temporal
  #     - server
  #   environment:
  #     SERVER_URL: server:3000
  #     PROCESS_EMAILS_ENDPOINT: /emails/processEmails
  #   networks:
  #     - default

networks:
  default:
    driver: bridge
    name: mentium-net
